import type { Pipeline } from "@/shared/types";

export const MOCK_PIPELINES: Pipeline[] = [
  {
    id: "traffic-intelligence",
    name: "Traffic Intelligence Pipeline",
    description: "Ingests traffic events, validates them and feeds the executive dashboard.",
    status: "success",
    lastRunAt: "2026-07-06T08:30:00Z",
    updatedAt: "2026-07-06T08:30:00Z",
    nodes: [
      {
        id: "n-source",
        type: "source",
        label: "API Source",
        status: "success",
        rowsProcessed: 48_200,
        durationMs: 1_800,
      },
      {
        id: "n-clean",
        type: "cleaning",
        label: "Data Cleaning",
        status: "success",
        rowsProcessed: 47_950,
        durationMs: 3_200,
      },
      {
        id: "n-validate",
        type: "validation",
        label: "Schema Validation",
        status: "success",
        rowsProcessed: 47_913,
        durationMs: 2_100,
      },
      {
        id: "n-join",
        type: "join",
        label: "Join Reference Data",
        status: "success",
        rowsProcessed: 47_913,
        durationMs: 4_400,
      },
      {
        id: "n-anomaly",
        type: "anomaly",
        label: "Anomaly Detection",
        status: "warning",
        rowsProcessed: 47_913,
        durationMs: 6_700,
      },
      {
        id: "n-output",
        type: "output",
        label: "Dashboard Output",
        status: "success",
        rowsProcessed: 47_913,
        durationMs: 900,
      },
    ],
    edges: [
      { id: "e1", source: "n-source", target: "n-clean" },
      { id: "e2", source: "n-clean", target: "n-validate" },
      { id: "e3", source: "n-validate", target: "n-join" },
      { id: "e4", source: "n-join", target: "n-anomaly" },
      { id: "e5", source: "n-anomaly", target: "n-output" },
    ],
  },
  {
    id: "energy-forecast",
    name: "Energy Forecast Pipeline",
    description: "Aggregates energy telemetry and produces zone-level forecasts.",
    status: "failed",
    lastRunAt: "2026-07-06T07:15:00Z",
    updatedAt: "2026-07-06T07:15:00Z",
    nodes: [
      {
        id: "n-source",
        type: "source",
        label: "Telemetry Stream",
        status: "success",
        rowsProcessed: 50_000,
        durationMs: 2_500,
      },
      {
        id: "n-filter",
        type: "filter",
        label: "Filter Invalid Meters",
        status: "success",
        rowsProcessed: 49_120,
        durationMs: 1_400,
      },
      {
        id: "n-transform",
        type: "transformation",
        label: "Aggregate by Zone",
        status: "failed",
        durationMs: 5_300,
      },
      { id: "n-output", type: "output", label: "Forecast Output", status: "idle" },
    ],
    edges: [
      { id: "e1", source: "n-source", target: "n-filter" },
      { id: "e2", source: "n-filter", target: "n-transform" },
      { id: "e3", source: "n-transform", target: "n-output" },
    ],
  },
];
